server {
    # 1. Listen on port 443 for both IPv4 and IPv6
    listen 443 ssl;
    listen [::]:443 ssl;

    # 2. Set your mandatory domain name
    server_name ykhoussi.42.fr;

    # 3. Point to the SSL certificates we generated in the Dockerfile
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    # 4. Enforce the strict TLS protocol rules
    ssl_protocols TLSv1.2 TLSv1.3;

    # 5. Point to our magic portal folder
    root /var/www/html;
    index index.php index.html index.htm;

    # 6. Try to find the exact file requested, otherwise route to WordPress
    location / {
        try_files $uri $uri/ =404;
    }

    # 7. The bridge to the WordPress container
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass wordpress:9000;
    }
}