
services:
  mariadb:
    build: ./requirements/mariadb

    container_name: mariadb
    restart: always
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress

    container_name: wordpress
    restart: always
    env_file:
      - .env
    secrets:
      - db_password
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
  
  nginx:
    build: ./requirements/nginx

    container_name: nginx
    restart: always
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html

  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    restart: always
    networks:
      - inception
  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    restart: always
    env_file:
      - .env
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
  static_site:
    build: ./requirements/bonus/static_site
    container_name: static_site
    networks:
      - inception
    restart: always
  
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

  cadvisor:
    build: ./requirements/bonus/cadvisor
    container_name: cadvisor
    networks:
      - inception
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ykhoussi/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ykhoussi/data/wordpress

# --- Secrets Definition ---
secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt