
services:
  mariadb:
    build: ./requirements/mariadb

    container_name: mariadb
    restart: always
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress

    container_name: wordpress
    restart: always
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
  
  nginx:
    build: ./requirements/nginx

    container_name: nginx
    restart: always
    # Map port 443 on your VM host to port 443 inside the NGINX container
    ports:
      - "443:443"
    networks:
      - inception
    # Mount the exact same volume that WordPress is using
    volumes:
      - wordpress_data:/var/www/html

  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    restart: always
    networks:
      - inception
  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    restart: always
    env_file:
      - .env
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
  static_site:
    build: ./requirements/bonus/static_site
    container_name: static_site
    networks:
      - inception
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ykhoussi/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ykhoussi/data/wordpress

